imports:
    - { resource: services/commands.yml }
    - { resource: services/controllers.yml }
    - { resource: services/event_listeners.yml }
    - { resource: services/form_types.yml }
    - { resource: services/repositories.yml }

services:
#    app.service.example:
#        class: App\ExampleService
#        arguments: ['@service_name', 'plain_value', '%parameter_name%']
