services:
#    app.command.example:
#        class: App\Command\ExampleCommand
#        arguments: ["@service_name", "plain_value", "%parameter_name%"]
#        tags:
#            - { name: console.command }
