services:
#    app.example_type:
#        class: App\Form\ExampleType
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
#        tags:
#            - { name: form.type }
