services:
#    app.repository.abstract:
#        factory: ["@doctrine.orm.entity_manager", getRepository]
#        abstract: true
#        public: false
#
#    app.repository.example:
#        class: App\Repository\ExampleRepository
#        parent: app.abstract_repository
#        arguments: [App\Entity\ExampleEntity]
